feat: create stat-service
realkireev/java-explore-with-me pull request #3
Opened 2023-07-02 23:42 UTC by realkireev

2023-07-03 20:20 UTC, Donald522 commented
Привет!
ПР выглядит странно, как будто бы он уже был вмержен в main.

2023-07-03 20:21 UTC, Donald522 requested changes
Посмотри, почему изменения так выглядят. Тут явно не вся работа.

2023-07-03 20:52 UTC, realkireev commented
> Привет!
> ПР выглядит странно, как будто бы он уже был вмержен в main.

Привет! Я случайно все сделал в ветке main и запушил ее в гит, и только после этого заметил. Поэтому я откатил все изменения локально, запушил снова в гит пустой первоначальный код, создал ветку и уже внес функционал в нее. Видимо что-то не сработало и теперь выглядит так. Я могу начать вообще с нуля, если подскажешь как получить новый инвайт от Практикума, а этот репо могу грохнуть

2023-07-04 07:38 UTC, realkireev commented
Исправил ситуацию, откатился до начального коммита и ПР теперь нормальный.
Прошу проверить.

2023-07-04 07:41 UTC, realkireev commented
Да, защиту на main поставил и буду это теперь обязательно делать.

2023-07-04 20:07 UTC, Donald522 approved these changes
Привет!
На эту работу дается 2 итерации, поэтому я сейчас принимаю, а замечания поправь в рамках следующего спринта.

2023-07-04 20:07 UTC, Donald522 commented on stat-service/stat-service-client/src/main/java/ru/practicum/client/StatisticsClient.java
> +        ObjectMapper objectMapper = new ObjectMapper();
Вот это надо выносить в конфиг. Иначе в разных местах кода будут разные парсеры по-разному сконфигурированные. Это грабли, разложенные на будущее.

2023-07-04 20:07 UTC, Donald522 commented on stat-service/stat-service-client/src/main/java/ru/practicum/client/StatisticsClient.java
> +public class StatisticsClient {
А где метод получения статистики?

2023-07-04 20:07 UTC, Donald522 commented on stat-service/stat-service-server/src/main/java/ru/practicum/repo/HitRepository.java
> +    List<HitResponseDto> countAllBetween(@Param("start") LocalDateTime start, @Param("end") LocalDateTime end);
Репозиторий не должен работать с dto моделями

2023-07-04 20:07 UTC, Donald522 commented on stat-service/stat-service-server/src/main/java/ru/practicum/controller/HitController.java
> +        hitService.saveHit(hitRequestDto);
Логирования не хватает

2023-07-04 20:07 UTC, Donald522 commented on stat-service/stat-service-server/src/main/resources/schema.sql
> +    uri VARCHAR(1000) NOT NULL,
На uri и timestamp надо добавить индексы

2023-07-05 15:44 UTC, merged