feat: moderation_enhancement
realkireev/java-explore-with-me pull request #5
Opened 2023-07-19 12:01 UTC by realkireev

Прошу проверить фичу, было выбрано администрирование, второй вариант:

Улучшение модерации событий администратором — возможность выгружать все события, ожидающие модерации, делать их проверку, а также оставлять комментарий для инициатора события, если оно не прошло модерацию. При этом у инициатора есть возможность исправить замечания и отправить событие на повторную модерацию.

2023-07-19 21:24 UTC, Donald522 requested changes
Привет!

Не уверен, насколько правильно предъявлять нефункциональные требования к работе, но в будущем ты с этим в любом случае столкнешься.

А так вроде бы все хорошо.

2023-07-19 21:24 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/repo/EventRepository.java
> +    @Query("SELECT e.state, COUNT(e) AS count FROM Event e GROUP BY e.state")
На продакшн объемах этот запрос положит базу
В интернете можно дольно много найти про производительность count. Даже на миллионе строк простой count без группировки будет выполняться секунды (это очень много)

Агрегаты надо считать не в момент читающего запроса, а в момент пишущего, те когда что-то меняется

2023-07-19 21:24 UTC, Donald522 commented on ewm-service/src/main/java/ru/practicum/controller/adminapi/AdminEventController.java
> +        return eventService.getEvents(null, List.of(EventState.PENDING), null, null, null, from,
Я не проверял предыдущий спринт, но без индексов в таблице events это не будет работать нормально

2023-07-20 22:14 UTC, realkireev commented on ewm-service/src/main/java/ru/practicum/repo/EventRepository.java
> +    @Query("SELECT e.state, COUNT(e) AS count FROM Event e GROUP BY e.state")
Сделал сохранение статистики в момент записи.

2023-07-20 22:14 UTC, realkireev commented on ewm-service/src/main/java/ru/practicum/controller/adminapi/AdminEventController.java
> +        return eventService.getEvents(null, List.of(EventState.PENDING), null, null, null, from,
Сделал индексы.

2023-07-20 22:14 UTC, realkireev commented
Постарался все сделать как надо, прошу проверить.

2023-07-21 07:18 UTC, Donald522 approved these changes

2023-07-24 15:06 UTC, merged